---
# handlers file for ansible_cool_lab_app
- name: "Start {{ cool_lab_app_name }}"
  ansible.builtin.systemd:
    name: "{{ cool_lab_app_name }}"
    state: started
    enabled: yes

- name: "Restarted {{ cool_lab_app_name }}"
  ansible.builtin.systemd:
    name: "{{ cool_lab_app_name }}"
    state: restarted
    enabled: yes